In [2]:
import numpy as np
import pandas as pd

# Introduction to Pandas

## What is pandas?
Pandas is an open source Python package that is built on top of Numpy. It provides many methods that help in the most routine an ubiquitous tasks in data science and analysis.

Good overview:
https://www.youtube.com/watch?v=dcqPhpY7tWk

## Data Structures In Pandas

The fundamental data structures are:

* `Series` - 1-d data structure that is analagous to a column in a spreadsheet.

* `DataFrame` - 2-D structure that is analgous to a sheet in an excel . Collection of pandas `Series` objects.


More info here:
https://pandas.pydata.org/docs/user_guide/dsintro.html

### Creating and Manipulating `Series` objects
`Series` objects can be created from lists or `np.array` objects

#### Creating Pandas `Series` Objects

In [6]:
# Lets create a Series from a list
l = list(range(10,20))
l_series = pd.Series(l)
l_series

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [15]:
# Lets create the same series from a numpy array
n = np.arange(10,20)
n_series = pd.Series(n)
n_series

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

__NOTE:__ The `Series` has the data (2nd column) and an Index (1st column). We can specify the idicie names when we create the `Series`

In [9]:
l = [10,20,30,40]
l_series = pd.Series(
  l,
  index=["a","b","c","d"],
  dtype=float
)
l_series

a    10.0
b    20.0
c    30.0
d    40.0
dtype: float64

In [25]:
# If we know the indicies we can create a series directly from a dictionaary
d = {
    "a":10,
    "b":20,
    "c":30,
    "d":40
}
d_series = pd.Series(d)
d_series

a    10
b    20
c    30
d    40
dtype: int64

In [30]:
# Or from two lists
l = [10,20,30,40]
i = ["a","b","c","d"]
z_series = pd.Series(l,i, dtype=float)
z_series

a    10.0
b    20.0
c    30.0
d    40.0
dtype: float64

__NOTE:__ we can also specify the dtype

In [18]:
# Series can hold any and all types
my_series = pd.Series(
    ["germany", "germany", "germany", "japan", "korea", 2, True],
    index=["bmw", "audi", "mercedes", "lexus", "genesis", "unk", "what?"]
  )
my_series

bmw         germany
audi        germany
mercedes    germany
lexus         japan
genesis       korea
unk               2
what?          True
dtype: object

In [24]:
# just to confirm types
print('type for "bmw"',type(my_series["bmw"]))
print('type for "unk"', type(my_series["unk"]))
print('type for "what?"', type(my_series["what?"]))

type for "bmw" <class 'str'>
type for "unk" <class 'int'>
type for "what?" <class 'bool'>

#### Accessing Elements of Pandas `Series` Objects

In [10]:
# Accessing elements within a series with a index number
l_series[0]

10.0

In [11]:
# We can access elements within a series with label
l_series['a']

10.0

In [12]:
# we can also access groups of elements
l_series['a':'c']

a    10.0
b    20.0
c    30.0
dtype: float64

In [161]:
# How about every element after the name "b" (inclusive)?
l_series["b":]

b    20.0
c    30.0
d    40.0
dtype: float64

In [14]:
# or a list of rows
l_series[["a","c"]]

a    10.0
c    30.0
dtype: float64

In [33]:
# How about using negative ranges?
l_series[-3:]

b    20.0
c    30.0
d    40.0
dtype: float64

In [160]:
# what about the first two elements?
l_series[:2]

a    10.0
b    20.0
dtype: float64

#### Simple operations on `Series` Objects

In [36]:
# Lets Create 2 Series objects with the same indicies

a = pd.Series(
    {
        "a":10,
        "b":20,
        "c":30,
        "d":40,
    }
)

a

a    10
b    20
c    30
d    40
dtype: int64

In [50]:
b = pd.Series(
    {
        "d":10,
        "c":20,
        "b":30,
        "a":40,
    }
)
b

d    10
c    20
b    30
a    40
dtype: int64

In [51]:
# Lets perform some operations

print(f"addition:\n{a + b}")
print(f"subtraction:\n{a - b}")
print(f"multiplication:\n{a * b}")
print(f"division:\n{a/b}")
print(f"powers:\n{a**b}")
print(f"addition of a constant:\n{b + 10}")

addition:
a    50
b    50
c    50
d    50
dtype: int64
subtraction:
a   -30
b   -10
c    10
d    30
dtype: int64
multiplication:
a    400
b    600
c    600
d    400
dtype: int64
division:
a    0.250000
b    0.666667
c    1.500000
d    4.000000
dtype: float64
powers:
a   -5047021154770878464
b   -8070450532247928832
c   -4356359181443268608
d      10485760000000000
dtype: int64
addition of a constant:
d    20
c    30
b    40
a    50
dtype: int64

__NOTE:__ Operations are done element-wise, just like a `numpy.array` object

__NOTE:__ Indicies do not need to be in the same order. Pandas aligns the keys.

### Creating and Manipulating `DataFrame` objects

#### Creating `DataFrame` Objects

More examples can be found here: https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/

In [52]:
# Lets start by creating a DataFrame from a list
l = [10,20,30,40]
l_df = pd.DataFrame(
    l,
    index=["a","b","c","d"]
)
l_df

    0
a  10
b  20
c  30
d  40

__NOTE:__ That the column indecies have been named, but the column (`Series`) itself does not have a name associated with it.

In [56]:
# Lets recreate it with a name...
l = [10,20,30,40]
l_df = pd.DataFrame(
    l,
    index=["a","b","c","d"],
    columns=["values"]
)
l_df

   values
a      10
b      20
c      30
d      40

In [60]:
# Lets make do this with a pd.Series
l = [10,20,30,40]
l_s = pd.Series(
    l,
    index=["a","b","c","d"],
)
l_df = pd.DataFrame(
    l_s,
    columns=["values"]
)
l_df

   values
a      10
b      20
c      30
d      40

In [59]:
# We can also do this with dictionaries
df = pd.DataFrame(
    {"values": l_s}
)
df

   values
a      10
b      20
c      30
d      40

In [63]:
# What if we want to create a data frame with multiple columns
students = ["foo", "bar", "hello", "world"]
grades = ["F", "A-", "C", "B"]
df = pd.DataFrame(
    {"Students": students, "Grades": grades}
)
df

  Students Grades
0      foo      F
1      bar     A-
2    hello      C
3    world      B

__NOTE:__ If you are creating a `DataFrame` as above, all lists need to be the same length. If not the following error is generated:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-62-19aeb77092a8> in <cell line: 4>()
      2 students = ["foo", "bar", "hello", "world"]
      3 grades = ["F", "A-", "C"]
----> 4 df = pd.DataFrame(
      5     {"Students": students, "Grades": grades}
      6 )

3 frames
/usr/local/lib/python3.10/dist-packages/pandas/core/internals/construction.py in _extract_index(data)
    664             lengths = list(set(raw_lengths))
    665             if len(lengths) > 1:
--> 666                 raise ValueError("All arrays must be of the same length")
    667
    668             if have_dicts:

ValueError: All arrays must be of the same length
```

In [65]:
# We could also do the same with pandas Series
students = pd.Series(["foo", "bar", "hello", "world"])
grades = pd.Series(["F", "A-", "C", "B"])
df = pd.DataFrame(
    {"Students": students, "Grades": grades}
)
df

  Students Grades
0      foo      F
1      bar     A-
2    hello      C
3    world      B

#### Accesssing Elements in a `DataFrame`
__NOTE:__ When you want to access rows you need to use `loc` and `iloc`

* Use `loc` when access a row by name
* Use `iloc` when accessing row by index number

__NOTE:__ Like other python objects, if you slice a `DataFrame` and then change a value in the slice, the original is also modified (still reference based)

In [139]:
# Lets create a DataFrame of student grades on a set of 3 tests
student_names = ["foo", "bar", "hello", "world"]
num_tests = 3

In [140]:
# Lets create some random scores for 3 tests
test_scores = np.absolute(np.random.randn(len(student_names), num_tests))

# scale the normally distributed between 0 and 100 based on the max of the
# absolute value of each test (column)
# round to the nearest integer
test_scores = np.round(test_scores/test_scores.max(axis=0)*100)

test_scores

array([[100., 100.,  12.],
       [ 56.,  48.,  13.],
       [ 67.,  14., 100.],
       [ 49.,  60.,  57.]])

In [141]:
# Now let's create the DataFrame
test_data = pd.DataFrame(
    test_scores,
    columns = ["Test1", "Test2", "Test3"],
    index=student_names
)
test_data

       Test1  Test2  Test3
foo    100.0  100.0   12.0
bar     56.0   48.0   13.0
hello   67.0   14.0  100.0
world   49.0   60.0   57.0

In [142]:
# what are all the students grades for Test 1
test_data["Test1"]

foo      100.0
bar       56.0
hello     67.0
world     49.0
Name: Test1, dtype: float64

In [143]:
# What were the scores for the last test?
test_data.iloc[:,-1]

foo       12.0
bar       13.0
hello    100.0
world     57.0
Name: Test3, dtype: float64

In [147]:
# what were student "bar"'s grades?
test_data.loc["bar"]

Test1    56.0
Test2    48.0
Test3    13.0
Name: bar, dtype: float64

In [148]:
# What was the average for each student
test_data.mean(axis=1)

foo      70.666667
bar      39.000000
hello    60.333333
world    55.333333
dtype: float64

In [149]:
# what is the standard deviation for each student?
test_data.std(axis=1)

foo      50.806824
bar      22.869193
hello    43.385866
world     5.686241
dtype: float64

In [128]:
# what was the average for each test?
test_data.mean(axis=0)

Test1    44.25
Test2    60.50
Test3    50.75
dtype: float64

In [150]:
# what was the standard deviation for each test?
test_data.std(axis=0)

Test1    22.583180
Test2    35.491783
Test3    41.956326
dtype: float64

In [129]:
# What were the last students grades?
test_data.iloc[-1]

Test1     27.0
Test2    100.0
Test3     48.0
Name: world, dtype: float64

In [130]:
# What is the name of the last student?
test_data.iloc[-1].name

'world'

In [131]:
# What grade did the second to last student get, on the second to last test?
test_data.iloc[-2,-2]

75.0

In [152]:
# What are the scores for the "bar" and "hello"
bar_hello = test_data["bar":"hello"]
bar_hello

       Test1  Test2  Test3
bar     56.0   48.0   13.0
hello   67.0   14.0  100.0

In [158]:
# what is the type of object for "bar_hello"?
type(bar_hello)

pandas.core.frame.DataFrame

In [159]:
# If we change a score of Test2 for student "bar" in "bar_hello",
# is it reflected in test_data?
bar_hello.loc['bar','Test2'] = 100.0
test_data

       Test1  Test2  Test3
foo    100.0  100.0   12.0
bar     56.0  100.0   13.0
hello   67.0   14.0  100.0
world   49.0   60.0   57.0

# Example: Store Data

## Introduction
This example is from the lecture video: *1.2.2 Accessing Series and DataFrames using Pandas*

## Description
In this example we take a data frame that contains fictitious store purchase data and apply filters and slicing to pull out specific data.

In [164]:
# Let's start by creating a data set that we will manipulate
store_data = pd.DataFrame(
    {
        "CustomerID": ['CustID00', 'CustID01', 'CustID02', 'CustID03', 'CustID04'],
        "location": ["Chicago", "Boston", "Seattle", "San Francisco", "Austin"],
        "gender": ["M", "M", "F", "M", "F"],
        "type": [
            "Electronics",
            "Food&Beverages",
            "Food&Beverages",
            "Medicine",
            "Beauty"
        ],
        "quantity": [1, 3, 4, 2, 1],
        "total_bill" : [100, 75, 125, 50, 80]
    }
)
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [165]:
# Get the first row of the DataFrame
store_data[:1]

  CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100

In [172]:
# Lets get the first column of data by index
store_data[store_data.columns[1]]

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [179]:
# What is the name of the first column?
store_data.columns[1]

'location'

In [173]:
# If we know the name of the column we can just use that:
store_data['location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [174]:
# we can also just access it using `.` notation
store_data.location

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

__NOTE:__ `.` notation only works if the name has no spaces in it. Safer to use `[]` notation

In [176]:
# Lets get every other row
store_data[::2] #all columns, every other row

  CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80

In [177]:
# Access every other row in reverse
store_data[::-2]

  CustomerID location gender            type  quantity  total_bill
4   CustID04   Austin      F          Beauty         1          80
2   CustID02  Seattle      F  Food&Beverages         4         125
0   CustID00  Chicago      M     Electronics         1         100

In [178]:
# reverse the rows of the DataFrame
store_data[::-1]

  CustomerID       location gender            type  quantity  total_bill
4   CustID04         Austin      F          Beauty         1          80
3   CustID03  San Francisco      M        Medicine         2          50
2   CustID02        Seattle      F  Food&Beverages         4         125
1   CustID01         Boston      M  Food&Beverages         3          75
0   CustID00        Chicago      M     Electronics         1         100

# `loc` and `iloc` in Depth

`loc` and `iloc` allow you to slice, and access rows and columns in a Pandas `DataFrame`. `loc` is label based, whilst `iloc` is integer based:

* dataframe.`loc`[\<row __label__ selection>, \<column __label__ selection>]


* dataframe.`iloc`[\<row __integer__ selection>, \<column __integer__ selection>]*

❗ __NOTE:__ the use of `[]` and not `()` when using `.loc` and `iloc` ❗

In [303]:
# Lets recreated the store data from the example
store_data = pd.DataFrame(
    {
        "CustomerID": ['CustID00', 'CustID01', 'CustID02', 'CustID03', 'CustID04'],
        "location": ["Chicago", "Boston", "Seattle", "San Francisco", "Austin"],
        "gender": ["M", "M", "F", "M", "F"],
        "type": [
            "Electronics",
            "Food&Beverages",
            "Food&Beverages",
            "Medicine",
            "Beauty"
        ],
        "quantity": [1, 3, 4, 2, 1],
        "total_bill" : [100, 75, 125, 50, 80]
    }
)
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [304]:
# lets access the first row
store_data.loc[1]

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1, dtype: object

In [305]:
# lets give the customer indicies a borg name
borg_names = [f"{i} of {len(store_data)}" for i in range(len(store_data))]
store_data.index = borg_names
store_data

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

In [264]:
# Now lets access the row for "1 of 5"
store_data.loc["1 of 5"]

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1 of 5, dtype: object

In [265]:
# we can still access the  row by number using iloc
store_data.iloc[1]

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1 of 5, dtype: object

In [194]:
# Now lets get the location and type data for the first and fourth customers

# First we need to get the names of the customers
customer_names = store_data.index[[1,4]]

# now we can use `loc` to get the location and type data
store_data.loc[customer_names, ['location', 'type']]

       location            type
1 of 5   Boston  Food&Beverages
4 of 5   Austin          Beauty

In [266]:
# doing the above with iloc we need to get the column numbers
col_numbers = [store_data.columns.get_loc(c) for c in store_data.columns if c in ['location', 'type'] ]

store_data.iloc[[1,4], col_numbers]

       location            type
1 of 5   Boston  Food&Beverages
4 of 5   Austin          Beauty

In [267]:
# Lets update the 'type' information for row 4 to 'Electronics'
col_number = store_data.columns.get_loc('type')
store_data.iloc[4,col_number] = "Electronics"
store_data

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F     Electronics         1          80

In [268]:
# let's change it back to beauty using the loc method
label = store_data.index[4]
store_data.loc[label, 'type'] = "Beauty"
store_data

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

# Condition Based Indexing in Pandas

In [269]:
# Let's apply a filter on the 'quantity' column
quant_gt_1 = store_data['quantity'] > 1
quant_gt_1

0 of 5    False
1 of 5     True
2 of 5     True
3 of 5     True
4 of 5    False
Name: quantity, dtype: bool

In [270]:
# now let's select the rows where this is True
store_data.loc[quant_gt_1]

       CustomerID       location gender            type  quantity  total_bill
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50

In [271]:
# lets select the rows where the quantity is not greater than one
store_data.loc[~quant_gt_1]

       CustomerID location gender         type  quantity  total_bill
0 of 5   CustID00  Chicago      M  Electronics         1         100
4 of 5   CustID04   Austin      F       Beauty         1          80

In [272]:
# lets further filter this where gender is female
store_data.loc[~quant_gt_1].loc[store_data['gender'] == "F"]

       CustomerID location gender    type  quantity  total_bill
4 of 5   CustID04   Austin      F  Beauty         1          80

In [273]:
# likewise get all the male customers that bought more than 1
store_data.loc[quant_gt_1].loc[store_data["gender"] == "M"]

       CustomerID       location gender            type  quantity  total_bill
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
3 of 5   CustID03  San Francisco      M        Medicine         2          50

In [274]:
# Lets get the average spend on "Food&Beverages"
spend = store_data.loc[store_data['type'] == "Food&Beverages"]["total_bill"]
spend

1 of 5     75
2 of 5    125
Name: total_bill, dtype: int64

In [275]:
spend.mean()

100.0

In [276]:
# Spend should be a pandas Series
type(spend)

pandas.core.series.Series

# Adding and Dropping Columns

In [330]:
# Lets recreated the store data from the example
store_data = pd.DataFrame(
    {
        "CustomerID": ['CustID00', 'CustID01', 'CustID02', 'CustID03', 'CustID04'],
        "location": ["Chicago", "Boston", "Seattle", "San Francisco", "Austin"],
        "gender": ["M", "M", "F", "M", "F"],
        "type": [
            "Electronics",
            "Food&Beverages",
            "Food&Beverages",
            "Medicine",
            "Beauty"
        ],
        "quantity": [1, 3, 4, 2, 1],
        "total_bill" : [100, 75, 125, 50, 80]
    }
)
# lets give the customer indicies a borg name
borg_names = [f"{i} of {len(store_data)}" for i in range(len(store_data))]
store_data.index = borg_names
store_data

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

In [331]:
# Lets add a "ratings" column to the store_data
ratings = [2,5,3,4,4]
store_data['ratings'] = ratings
store_data

,CustomerID,location,gender,type,quantity,total_bill,ratings
0 of 5,CustID00,Chicago,M,Electronics,1,100,2
1 of 5,CustID01,Boston,M,Food&Beverages,3,75,5
2 of 5,CustID02,Seattle,F,Food&Beverages,4,125,3
3 of 5,CustID03,San Francisco,M,Medicine,2,50,4
4 of 5,CustID04,Austin,F,Beauty,1,80,4

In [332]:
# What if ratings was a Series object?
# First let's remove ratings
store_data = store_data.drop('ratings', axis=1)
store_data

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

❗__NOTE:__ Could have done the drop with `inplace=True` parameter as well ❗

In [333]:
# now let's create the Series
#
ratings = pd.Series(
    ratings,
    index = store_data.index
)
ratings

0 of 5    2
1 of 5    5
2 of 5    3
3 of 5    4
4 of 5    4
dtype: int64

❗ __NOTE:__ You need to make sure the `Series` has the same index lables as the `DataFrame` for this to work ❗

In [334]:
store_data['ratings'] = ratings
store_data

,CustomerID,location,gender,type,quantity,total_bill,ratings
0 of 5,CustID00,Chicago,M,Electronics,1,100,2
1 of 5,CustID01,Boston,M,Food&Beverages,3,75,5
2 of 5,CustID02,Seattle,F,Food&Beverages,4,125,3
3 of 5,CustID03,San Francisco,M,Medicine,2,50,4
4 of 5,CustID04,Austin,F,Beauty,1,80,4

In [335]:
# Lets copy the total_bill and ratings to a new data frame
temp_df = store_data[["total_bill", "ratings"]].copy()
temp_df

        total_bill  ratings
0 of 5         100        2
1 of 5          75        5
2 of 5         125        3
3 of 5          50        4
4 of 5          80        4

In [336]:
# Now let's drop the original columns from the store_data usin inplace parameter
store_data.drop(["total_bill", "ratings"], axis=1, inplace=True)
store_data

       CustomerID       location gender            type  quantity
0 of 5   CustID00        Chicago      M     Electronics         1
1 of 5   CustID01         Boston      M  Food&Beverages         3
2 of 5   CustID02        Seattle      F  Food&Beverages         4
3 of 5   CustID03  San Francisco      M        Medicine         2
4 of 5   CustID04         Austin      F          Beauty         1

In [337]:
# now lets add it them back in using the join method
store_data = store_data.join(temp_df)
store_data

,CustomerID,location,gender,type,quantity,total_bill,ratings
0 of 5,CustID00,Chicago,M,Electronics,1,100,2
1 of 5,CustID01,Boston,M,Food&Beverages,3,75,5
2 of 5,CustID02,Seattle,F,Food&Beverages,4,125,3
3 of 5,CustID03,San Francisco,M,Medicine,2,50,4
4 of 5,CustID04,Austin,F,Beauty,1,80,4

# Adding and Dropping Rows

In [34]:
# Lets recreated the store data from the example
store_data = pd.DataFrame(
    {
        "CustomerID": ['CustID00', 'CustID01', 'CustID02', 'CustID03', 'CustID04'],
        "location": ["Chicago", "Boston", "Seattle", "San Francisco", "Austin"],
        "gender": ["M", "M", "F", "M", "F"],
        "type": [
            "Electronics",
            "Food&Beverages",
            "Food&Beverages",
            "Medicine",
            "Beauty"
        ],
        "quantity": [1, 3, 4, 2, 1],
        "total_bill" : [100, 75, 125, 50, 80]
    }
)
# lets give the customer indicies a borg name
borg_names = [f"{i} of {len(store_data)}" for i in range(len(store_data))]
store_data.index = borg_names
store_data

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

In [35]:
# Now copy the first row to a new data frame
first = store_data.iloc[0].copy()
first

CustomerID       CustID00
location          Chicago
gender                  M
type          Electronics
quantity                1
total_bill            100
Name: 0 of 5, dtype: object

In [36]:
type(first)

pandas.core.series.Series

In [37]:
# lets drop the first row
store_data.drop(first.name, axis=0, inplace=True)
store_data

       CustomerID       location gender            type  quantity  total_bill
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

In [38]:
#now lets add it back in with
store_data.loc[first.name] = first
store_data.sort_values('CustomerID')

       CustomerID       location gender            type  quantity  total_bill
0 of 5   CustID00        Chicago      M     Electronics         1         100
1 of 5   CustID01         Boston      M  Food&Beverages         3          75
2 of 5   CustID02        Seattle      F  Food&Beverages         4         125
3 of 5   CustID03  San Francisco      M        Medicine         2          50
4 of 5   CustID04         Austin      F          Beauty         1          80

# Combining `DataFrames`

In [3]:
# Lets create a DataFrame of customers
customers = pd.DataFrame(
    {
        "CustomerID": ['CustID00', 'CustID01', 'CustID02', 'CustID03', 'CustID04'],
        "location": ["Chicago", "Boston", "Seattle", "San Francisco", "Austin"],
        "gender": ["M", "M", "F", "M", "F"],
        "type": [
            "Electronics",
            "Food&Beverages",
            "Food&Beverages",
            "Medicine",
            "Beauty"
        ],
        "quantity": [1, 3, 4, 2, 1],
        "total_bill" : [100, 75, 125, 50, 80]
    }
)

customers

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [4]:
# Lets create a new customer data set NOTE the replicated CustID00, with
# Quantity and bill
new_customers = pd.DataFrame(
    {
        "CustomerID": ['CustID05', 'CustID06', 'CustID07', 'CustID08', 'CustID09', "CustID00"],
        "location": ["Los Angeles", "Portland", "Washington", "Dallas", "Atlanta", "Chicago"],
        "Date": ["2023-07-15", "2023-07-14", "2023-07-15", "2023-07-15", "2023-07-14", "2023-07-14"],
        "gender": ["F", "M", "F", "M", "F", "M"],
        "quantity": [1, 3, 4, 2, 1, 10],
        "total_bill" : [100, 75, 125, 50, 80, 1000]
    }
)
new_customers

  CustomerID     location        Date gender  quantity  total_bill
0   CustID05  Los Angeles  2023-07-15      F         1         100
1   CustID06     Portland  2023-07-14      M         3          75
2   CustID07   Washington  2023-07-15      F         4         125
3   CustID08       Dallas  2023-07-15      M         2          50
4   CustID09      Atlanta  2023-07-14      F         1          80
5   CustID00      Chicago  2023-07-14      M        10        1000

## `pd.concat`

Append two data frames along a spcific axis, either rows, or on top of, (`axis=0`) or columns, next to, (`axis=1`) each other

In [5]:
# To concatenate two DataFrames along the row axis
all_customers = pd.concat([customers, new_customers], axis=0).reset_index(drop=True)
all_customers

,CustomerID,location,gender,type,quantity,total_bill,Date
0,CustID00,Chicago,M,Electronics,1,100,NaN
1,CustID01,Boston,M,Food&Beverages,3,75,NaN
2,CustID02,Seattle,F,Food&Beverages,4,125,NaN
3,CustID03,San Francisco,M,Medicine,2,50,NaN
4,CustID04,Austin,F,Beauty,1,80,NaN
5,CustID05,Los Angeles,F,NaN,1,100,2023-07-15
6,CustID06,Portland,M,NaN,3,75,2023-07-14
7,CustID07,Washington,F,NaN,4,125,2023-07-15
8,CustID08,Dallas,M,NaN,2,50,2023-07-15
9,CustID09,Atlanta,F,NaN,1,80,2023-07-14
10,CustID00,Chicago,M,NaN,10,1000,2023-07-14

❗__NOTE:__ That, `pd.concat` will take a union of the set of all columns in both `DataFrames`, and populate missing values with a `NaN`. ❗

In [7]:
# For the sake of being complete, lets concatenate along the columns axis
pd.concat([customers, new_customers], axis=1).reset_index(drop=True)

,CustomerID,location,gender,type,quantity,total_bill,CustomerID,location,Date,gender,quantity,total_bill
0,CustID00,Chicago,M,Electronics,1.0,100.0,CustID05,Los Angeles,2023-07-15,F,1,100
1,CustID01,Boston,M,Food&Beverages,3.0,75.0,CustID06,Portland,2023-07-14,M,3,75
2,CustID02,Seattle,F,Food&Beverages,4.0,125.0,CustID07,Washington,2023-07-15,F,4,125
3,CustID03,San Francisco,M,Medicine,2.0,50.0,CustID08,Dallas,2023-07-15,M,2,50
4,CustID04,Austin,F,Beauty,1.0,80.0,CustID09,Atlanta,2023-07-14,F,1,80
5,NaN,NaN,NaN,NaN,NaN,NaN,CustID00,Chicago,2023-07-14,M,10,1000

__NOTE:__ In this case, `pd.concat` has used the `index` to align the data. So it assumes that columns from both `DataFrames` are aligned. Also note that it has filled in `NaN` for some columns due to the difference in number of rows in the `DataFrame`s.

## `pd.merge`

`merge` Combines `DataFrames` using a column's value to identify common entries.

More info can be found here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

In [8]:
# Since there is a common customerID in both DataFrames, lets merge the two
# using CustomerID's value as the common column.
pd.merge(customers, new_customers, how="outer", on="CustomerID")

,CustomerID,location_x,gender_x,type,quantity_x,total_bill_x,location_y,Date,gender_y,quantity_y,total_bill_y
0,CustID00,Chicago,M,Electronics,1.0,100.0,Chicago,2023-07-14,M,10.0,1000.0
1,CustID01,Boston,M,Food&Beverages,3.0,75.0,NaN,NaN,NaN,NaN,NaN
2,CustID02,Seattle,F,Food&Beverages,4.0,125.0,NaN,NaN,NaN,NaN,NaN
3,CustID03,San Francisco,M,Medicine,2.0,50.0,NaN,NaN,NaN,NaN,NaN
4,CustID04,Austin,F,Beauty,1.0,80.0,NaN,NaN,NaN,NaN,NaN
5,CustID05,NaN,NaN,NaN,NaN,NaN,Los Angeles,2023-07-15,F,1.0,100.0
6,CustID06,NaN,NaN,NaN,NaN,NaN,Portland,2023-07-14,M,3.0,75.0
7,CustID07,NaN,NaN,NaN,NaN,NaN,Washington,2023-07-15,F,4.0,125.0
8,CustID08,NaN,NaN,NaN,NaN,NaN,Dallas,2023-07-15,M,2.0,50.0
9,CustID09,NaN,NaN,NaN,NaN,NaN,Atlanta,2023-07-14,F,1.0,80.0

In [10]:
# What if we merge on gender
pd.merge(customers, new_customers, how="outer", on="gender")

,CustomerID_x,location_x,gender,type,quantity_x,total_bill_x,CustomerID_y,location_y,Date,quantity_y,total_bill_y
0,CustID00,Chicago,M,Electronics,1,100,CustID06,Portland,2023-07-14,3,75
1,CustID00,Chicago,M,Electronics,1,100,CustID08,Dallas,2023-07-15,2,50
2,CustID00,Chicago,M,Electronics,1,100,CustID00,Chicago,2023-07-14,10,1000
3,CustID01,Boston,M,Food&Beverages,3,75,CustID06,Portland,2023-07-14,3,75
4,CustID01,Boston,M,Food&Beverages,3,75,CustID08,Dallas,2023-07-15,2,50
5,CustID01,Boston,M,Food&Beverages,3,75,CustID00,Chicago,2023-07-14,10,1000
6,CustID03,San Francisco,M,Medicine,2,50,CustID06,Portland,2023-07-14,3,75
7,CustID03,San Francisco,M,Medicine,2,50,CustID08,Dallas,2023-07-15,2,50
8,CustID03,San Francisco,M,Medicine,2,50,CustID00,Chicago,2023-07-14,10,1000
9,CustID02,Seattle,F,Food&Beverages,4,125,CustID05,Los Angeles,2023-07-15,1,100
10,CustID02,Seattle,F,Food&Beverages,4,125,CustID07,Washington,2023-07-15,4,125
11,CustID02,Seattle,F,Food&Beverages,4,125,CustID09,Atlanta,2023-07-14,1,80
12,CustID04,Austin,F,Beauty,1,80,CustID05,Los Angeles,2023-07-15,1,100
13,CustID04,Austin,F,Beauty,1,80,CustID07,Washington,2023-07-15,4,125
14,CustID04,Austin,F,Beauty,1,80,CustID09,Atlanta,2023-07-14,1,80

In [11]:
# merge on location
pd.merge(customers, new_customers, how="outer", on="location")

,CustomerID_x,location,gender_x,type,quantity_x,total_bill_x,CustomerID_y,Date,gender_y,quantity_y,total_bill_y
0,CustID00,Chicago,M,Electronics,1.0,100.0,CustID00,2023-07-14,M,10.0,1000.0
1,CustID01,Boston,M,Food&Beverages,3.0,75.0,NaN,NaN,NaN,NaN,NaN
2,CustID02,Seattle,F,Food&Beverages,4.0,125.0,NaN,NaN,NaN,NaN,NaN
3,CustID03,San Francisco,M,Medicine,2.0,50.0,NaN,NaN,NaN,NaN,NaN
4,CustID04,Austin,F,Beauty,1.0,80.0,NaN,NaN,NaN,NaN,NaN
5,NaN,Los Angeles,NaN,NaN,NaN,NaN,CustID05,2023-07-15,F,1.0,100.0
6,NaN,Portland,NaN,NaN,NaN,NaN,CustID06,2023-07-14,M,3.0,75.0
7,NaN,Washington,NaN,NaN,NaN,NaN,CustID07,2023-07-15,F,4.0,125.0
8,NaN,Dallas,NaN,NaN,NaN,NaN,CustID08,2023-07-15,M,2.0,50.0
9,NaN,Atlanta,NaN,NaN,NaN,NaN,CustID09,2023-07-14,F,1.0,80.0

Clearly, some merges make more sense than others

In [9]:
# If we leave out the "on" paramter, we end up doing a concat on rows (axis=0)
pd.merge(customers, new_customers, how="outer")

,CustomerID,location,gender,type,quantity,total_bill,Date
0,CustID00,Chicago,M,Electronics,1,100,NaN
1,CustID01,Boston,M,Food&Beverages,3,75,NaN
2,CustID02,Seattle,F,Food&Beverages,4,125,NaN
3,CustID03,San Francisco,M,Medicine,2,50,NaN
4,CustID04,Austin,F,Beauty,1,80,NaN
5,CustID05,Los Angeles,F,NaN,1,100,2023-07-15
6,CustID06,Portland,M,NaN,3,75,2023-07-14
7,CustID07,Washington,F,NaN,4,125,2023-07-15
8,CustID08,Dallas,M,NaN,2,50,2023-07-15
9,CustID09,Atlanta,F,NaN,1,80,2023-07-14
10,CustID00,Chicago,M,NaN,10,1000,2023-07-14

In [13]:
# what does "inner" do - only use the cusomer id values that are shared between
# (intersection) as the keys for the merge
pd.merge(customers, new_customers, how="inner", on="CustomerID")

,CustomerID,location_x,gender_x,type,quantity_x,total_bill_x,location_y,Date,gender_y,quantity_y,total_bill_y
0,CustID00,Chicago,M,Electronics,1,100,Chicago,2023-07-14,M,10,1000

In [85]:
# Only use customer id's from new_customers as the keys for the merge
pd.merge(customers, new_customers, how="right", on="CustomerID")

,CustomerID,location_x,gender_x,type,quantity_x,total_bill_x,location_y,gender_y,quantity_y,total_bill_y
0,CustID05,NaN,NaN,NaN,NaN,NaN,Los Angeles,F,1,100
1,CustID06,NaN,NaN,NaN,NaN,NaN,Portland,M,3,75
2,CustID07,NaN,NaN,NaN,NaN,NaN,Washington,F,4,125
3,CustID08,NaN,NaN,NaN,NaN,NaN,Dallas,M,2,50
4,CustID09,NaN,NaN,NaN,NaN,NaN,Atlanta,F,1,80

In [14]:
# only use the customer ID's from customers as the keys for the merge
pd.merge(customers, new_customers, how="left", on="CustomerID")

,CustomerID,location_x,gender_x,type,quantity_x,total_bill_x,location_y,Date,gender_y,quantity_y,total_bill_y
0,CustID00,Chicago,M,Electronics,1,100,Chicago,2023-07-14,M,10.0,1000.0
1,CustID01,Boston,M,Food&Beverages,3,75,NaN,NaN,NaN,NaN,NaN
2,CustID02,Seattle,F,Food&Beverages,4,125,NaN,NaN,NaN,NaN,NaN
3,CustID03,San Francisco,M,Medicine,2,50,NaN,NaN,NaN,NaN,NaN
4,CustID04,Austin,F,Beauty,1,80,NaN,NaN,NaN,NaN,NaN

In [16]:
# replicate each row in customers for each row in new_customers
pd.merge(customers, new_customers, how="cross")

,CustomerID_x,location_x,gender_x,type,quantity_x,total_bill_x,CustomerID_y,location_y,Date,gender_y,quantity_y,total_bill_y
0,CustID00,Chicago,M,Electronics,1,100,CustID05,Los Angeles,2023-07-15,F,1,100
1,CustID00,Chicago,M,Electronics,1,100,CustID06,Portland,2023-07-14,M,3,75
2,CustID00,Chicago,M,Electronics,1,100,CustID07,Washington,2023-07-15,F,4,125
3,CustID00,Chicago,M,Electronics,1,100,CustID08,Dallas,2023-07-15,M,2,50
4,CustID00,Chicago,M,Electronics,1,100,CustID09,Atlanta,2023-07-14,F,1,80
5,CustID00,Chicago,M,Electronics,1,100,CustID00,Chicago,2023-07-14,M,10,1000
6,CustID01,Boston,M,Food&Beverages,3,75,CustID05,Los Angeles,2023-07-15,F,1,100
7,CustID01,Boston,M,Food&Beverages,3,75,CustID06,Portland,2023-07-14,M,3,75
8,CustID01,Boston,M,Food&Beverages,3,75,CustID07,Washington,2023-07-15,F,4,125
9,CustID01,Boston,M,Food&Beverages,3,75,CustID08,Dallas,2023-07-15,M,2,50
10,CustID01,Boston,M,Food&Beverages,3,75,CustID09,Atlanta,2023-07-14,F,1,80
11,CustID01,Boston,M,Food&Beverages,3,75,CustID00,Chicago,2023-07-14,M,10,1000
12,CustID02,Seattle,F,Food&Beverages,4,125,CustID05,Los Angeles,2023-07-15,F,1,100
13,CustID02,Seattle,F,Food&Beverages,4,125,CustID06,Portland,2023-07-14,M,3,75
14,CustID02,Seattle,F,Food&Beverages,4,125,CustID07,Washington,2023-07-15,F,4,125
15,CustID02,Seattle,F,Food&Beverages,4,125,CustID08,Dallas,2023-07-15,M,2,50
16,CustID02,Seattle,F,Food&Beverages,4,125,CustID09,Atlanta,2023-07-14,F,1,80
17,CustID02,Seattle,F,Food&Beverages,4,125,CustID00,Chicago,2023-07-14,M,10,1000
18,CustID03,San Francisco,M,Medicine,2,50,CustID05,Los Angeles,2023-07-15,F,1,100
19,CustID03,San Francisco,M,Medicine,2,50,CustID06,Portland,2023-07-14,M,3,75
20,CustID03,San Francisco,M,Medicine,2,50,CustID07,Washington,2023-07-15,F,4,125
21,CustID03,San Francisco,M,Medicine,2,50,CustID08,Dallas,2023-07-15,M,2,50
22,CustID03,San Francisco,M,Medicine,2,50,CustID09,Atlanta,2023-07-14,F,1,80
23,CustID03,San Francisco,M,Medicine,2,50,CustID00,Chicago,2023-07-14,M,10,1000
24,CustID04,Austin,F,Beauty,1,80,CustID05,Los Angeles,2023-07-15,F,1,100
25,CustID04,Austin,F,Beauty,1,80,CustID06,Portland,2023-07-14,M,3,75
26,CustID04,Austin,F,Beauty,1,80,CustID07,Washington,2023-07-15,F,4,125
27,CustID04,Austin,F,Beauty,1,80,CustID08,Dallas,2023-07-15,M,2,50
28,CustID04,Austin,F,Beauty,1,80,CustID09,Atlanta,2023-07-14,F,1,80
29,CustID04,Austin,F,Beauty,1,80,CustID00,Chicago,2023-07-14,M,10,1000

## `pd.join`

Combine `DataFrames` using the index as the common key

More info can be found here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html

In [18]:
# As join expects common index keys, lets create a couple new DataFrames
quarters = pd.DataFrame(
    {
        "Q1": [102, 103, 104],
        "Q2": [201, 202, 203]
    },
    index=["I0", "I1", "I2"]
)
quarters

     Q1   Q2
I0  102  201
I1  103  202
I2  104  203

In [19]:
new_quarters = pd.DataFrame(
    {
        "Q3": [302, 303, 304],
        "Q4": [401, 402, 403]
    },
    index=["I0", "I1", "I2"]
)
new_quarters

     Q3   Q4
I0  302  401
I1  303  402
I2  304  403

In [20]:
# Now let's join the two
quarters.join(new_quarters)

     Q1   Q2   Q3   Q4
I0  102  201  302  401
I1  103  202  303  402
I2  104  203  304  403

So, because there are shared index's join uses those as the keys and appends the columns from `new_quarters` onto the columns in `quarters`

In [23]:
# Lets redefine new quarters to have an extra row
new_quarters = pd.DataFrame(
    {
        "Q3": [302, 303, 304, 305],
        "Q4": [401, 402, 403, 405]
    },
    index=["I0", "I1", "I2", "I3"]
)
new_quarters

     Q3   Q4
I0  302  401
I1  303  402
I2  304  403
I3  305  405

In [22]:
quarters.join(new_quarters)

     Q1   Q2   Q3   Q4
I0  102  201  302  401
I1  103  202  303  402
I2  104  203  304  403

__NOTE:__ that only the shared keys are preserved in the joined `DataFrame`
This is because we are, by default, using a "left" join.

In [25]:
# let do a "right" join
quarters.join(new_quarters, how="right")

       Q1     Q2   Q3   Q4
I0  102.0  201.0  302  401
I1  103.0  202.0  303  402
I2  104.0  203.0  304  403
I3    NaN    NaN  305  405

Now we get all the rows, but with `NaN` for missing values

In [26]:
# For this next part, lets redefine quarters to have another index as well
quarters = pd.DataFrame(
    {
        "Q1": [102, 103, 104, 105],
        "Q2": [202, 203, 204, 205]
    },
    index=["I0", "I1", "I2","I4"]
)
quarters

     Q1   Q2
I0  102  202
I1  103  203
I2  104  204
I4  105  205

In [27]:
# Now let's do an outer (union of indicies) join
quarters.join(new_quarters, how="outer")

       Q1     Q2     Q3     Q4
I0  102.0  202.0  302.0  401.0
I1  103.0  203.0  303.0  402.0
I2  104.0  204.0  304.0  403.0
I3    NaN    NaN  305.0  405.0
I4  105.0  205.0    NaN    NaN

Nice! Now we get all indicies, with `NaN` for values that are missing in either `quarters` or `new_quarters`

In [28]:
# Let's do an inner (intersection of indicies) join
quarters.join(new_quarters, how="inner")

     Q1   Q2   Q3   Q4
I0  102  202  302  401
I1  103  203  303  402
I2  104  204  304  403

Now we only get the indicies that are in both